# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skillruntime.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'skillruntime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12skillruntime.proto\x12\rconet.runtime\x1a\x1cgoogle/protobuf/struct.proto\"\xb4\x01\n\x0cSkillRequest\x12\x10\n\x08skill_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x10\n\x08trace_id\x18\x03 \x01(\t\x12\x14\n\x0c\x61uth_context\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x06 \x01(\x03\x12&\n\x05input\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"u\n\rSkillResponse\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.conet.runtime.Status\x12\'\n\x06output\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x14\n\x0c\x65rror_detail\x18\x03 \x01(\t\"@\n\nSkillChunk\x12\x0b\n\x03seq\x18\x01 \x01(\x05\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\" \n\rCancelRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"!\n\tCancelAck\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08*F\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x44\x45NIED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\r\n\tTIMED_OUT\x10\x03\x12\r\n\tCANCELLED\x10\x04\x32\xe1\x01\n\x0cSkillRuntime\x12\x44\n\x07\x45xecute\x12\x1b.conet.runtime.SkillRequest\x1a\x1c.conet.runtime.SkillResponse\x12I\n\rExecuteStream\x12\x1b.conet.runtime.SkillRequest\x1a\x19.conet.runtime.SkillChunk0\x01\x12@\n\x06\x43\x61ncel\x12\x1c.conet.runtime.CancelRequest\x1a\x18.conet.runtime.CancelAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skillruntime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=504
  _globals['_STATUS']._serialized_end=574
  _globals['_SKILLREQUEST']._serialized_start=68
  _globals['_SKILLREQUEST']._serialized_end=248
  _globals['_SKILLRESPONSE']._serialized_start=250
  _globals['_SKILLRESPONSE']._serialized_end=367
  _globals['_SKILLCHUNK']._serialized_start=369
  _globals['_SKILLCHUNK']._serialized_end=433
  _globals['_CANCELREQUEST']._serialized_start=435
  _globals['_CANCELREQUEST']._serialized_end=467
  _globals['_CANCELACK']._serialized_start=469
  _globals['_CANCELACK']._serialized_end=502
  _globals['_SKILLRUNTIME']._serialized_start=577
  _globals['_SKILLRUNTIME']._serialized_end=802
# @@protoc_insertion_point(module_scope)
