# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import skillruntime_pb2 as skillruntime__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in skillruntime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkillRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/conet.runtime.SkillRuntime/Execute',
                request_serializer=skillruntime__pb2.SkillRequest.SerializeToString,
                response_deserializer=skillruntime__pb2.SkillResponse.FromString,
                _registered_method=True)
        self.ExecuteStream = channel.unary_stream(
                '/conet.runtime.SkillRuntime/ExecuteStream',
                request_serializer=skillruntime__pb2.SkillRequest.SerializeToString,
                response_deserializer=skillruntime__pb2.SkillChunk.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/conet.runtime.SkillRuntime/Cancel',
                request_serializer=skillruntime__pb2.CancelRequest.SerializeToString,
                response_deserializer=skillruntime__pb2.CancelAck.FromString,
                _registered_method=True)


class SkillRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkillRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=skillruntime__pb2.SkillRequest.FromString,
                    response_serializer=skillruntime__pb2.SkillResponse.SerializeToString,
            ),
            'ExecuteStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteStream,
                    request_deserializer=skillruntime__pb2.SkillRequest.FromString,
                    response_serializer=skillruntime__pb2.SkillChunk.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=skillruntime__pb2.CancelRequest.FromString,
                    response_serializer=skillruntime__pb2.CancelAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conet.runtime.SkillRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conet.runtime.SkillRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkillRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conet.runtime.SkillRuntime/Execute',
            skillruntime__pb2.SkillRequest.SerializeToString,
            skillruntime__pb2.SkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conet.runtime.SkillRuntime/ExecuteStream',
            skillruntime__pb2.SkillRequest.SerializeToString,
            skillruntime__pb2.SkillChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conet.runtime.SkillRuntime/Cancel',
            skillruntime__pb2.CancelRequest.SerializeToString,
            skillruntime__pb2.CancelAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
